// Code generated by go-swagger; DO NOT EDIT.

// Package restapi watertower
//
//  Schemes:
//    http
//  Host: localhost:3000
//  BasePath: /
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
