// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModifyResponse ModifyResponse
//
// swagger:model ModifyResponse
type ModifyResponse struct {

	// id
	ID string `json:"_id,omitempty"`

	// index
	Index string `json:"_index,omitempty"`

	// primary term
	PrimaryTerm int64 `json:"_primary_term,omitempty"`

	// seq no
	SeqNo int64 `json:"_seq_no,omitempty"`

	// shards
	Shards *ModifyResponseShards `json:"_shards,omitempty"`

	// type
	Type string `json:"_type,omitempty"`

	// version
	Version int64 `json:"_version,omitempty"`

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this modify response
func (m *ModifyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShards(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModifyResponse) validateShards(formats strfmt.Registry) error {

	if swag.IsZero(m.Shards) { // not required
		return nil
	}

	if m.Shards != nil {
		if err := m.Shards.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_shards")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModifyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyResponse) UnmarshalBinary(b []byte) error {
	var res ModifyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ModifyResponseShards modify response shards
//
// swagger:model ModifyResponseShards
type ModifyResponseShards struct {

	// failed
	Failed int64 `json:"failed,omitempty"`

	// successful
	Successful int64 `json:"successful,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this modify response shards
func (m *ModifyResponseShards) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModifyResponseShards) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyResponseShards) UnmarshalBinary(b []byte) error {
	var res ModifyResponseShards
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
