// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetIndexDocIDOKCode is the HTTP code returned for type GetIndexDocIDOK
const GetIndexDocIDOKCode int = 200

/*GetIndexDocIDOK OK

swagger:response getIndexDocIdOK
*/
type GetIndexDocIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetIndexDocIDOKBody `json:"body,omitempty"`
}

// NewGetIndexDocIDOK creates GetIndexDocIDOK with default headers values
func NewGetIndexDocIDOK() *GetIndexDocIDOK {

	return &GetIndexDocIDOK{}
}

// WithPayload adds the payload to the get index doc Id o k response
func (o *GetIndexDocIDOK) WithPayload(payload *GetIndexDocIDOKBody) *GetIndexDocIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index doc Id o k response
func (o *GetIndexDocIDOK) SetPayload(payload *GetIndexDocIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexDocIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIndexDocIDBadRequestCode is the HTTP code returned for type GetIndexDocIDBadRequest
const GetIndexDocIDBadRequestCode int = 400

/*GetIndexDocIDBadRequest Bad Request

swagger:response getIndexDocIdBadRequest
*/
type GetIndexDocIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetIndexDocIDBadRequestBody `json:"body,omitempty"`
}

// NewGetIndexDocIDBadRequest creates GetIndexDocIDBadRequest with default headers values
func NewGetIndexDocIDBadRequest() *GetIndexDocIDBadRequest {

	return &GetIndexDocIDBadRequest{}
}

// WithPayload adds the payload to the get index doc Id bad request response
func (o *GetIndexDocIDBadRequest) WithPayload(payload *GetIndexDocIDBadRequestBody) *GetIndexDocIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index doc Id bad request response
func (o *GetIndexDocIDBadRequest) SetPayload(payload *GetIndexDocIDBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexDocIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIndexDocIDNotFoundCode is the HTTP code returned for type GetIndexDocIDNotFound
const GetIndexDocIDNotFoundCode int = 404

/*GetIndexDocIDNotFound Not Found

swagger:response getIndexDocIdNotFound
*/
type GetIndexDocIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *GetIndexDocIDNotFoundBody `json:"body,omitempty"`
}

// NewGetIndexDocIDNotFound creates GetIndexDocIDNotFound with default headers values
func NewGetIndexDocIDNotFound() *GetIndexDocIDNotFound {

	return &GetIndexDocIDNotFound{}
}

// WithPayload adds the payload to the get index doc Id not found response
func (o *GetIndexDocIDNotFound) WithPayload(payload *GetIndexDocIDNotFoundBody) *GetIndexDocIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index doc Id not found response
func (o *GetIndexDocIDNotFound) SetPayload(payload *GetIndexDocIDNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexDocIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
