// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetIndexSearchOKCode is the HTTP code returned for type GetIndexSearchOK
const GetIndexSearchOKCode int = 200

/*GetIndexSearchOK OK

swagger:response getIndexSearchOK
*/
type GetIndexSearchOK struct {

	/*
	  In: Body
	*/
	Payload *GetIndexSearchOKBody `json:"body,omitempty"`
}

// NewGetIndexSearchOK creates GetIndexSearchOK with default headers values
func NewGetIndexSearchOK() *GetIndexSearchOK {

	return &GetIndexSearchOK{}
}

// WithPayload adds the payload to the get index search o k response
func (o *GetIndexSearchOK) WithPayload(payload *GetIndexSearchOKBody) *GetIndexSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index search o k response
func (o *GetIndexSearchOK) SetPayload(payload *GetIndexSearchOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIndexSearchBadRequestCode is the HTTP code returned for type GetIndexSearchBadRequest
const GetIndexSearchBadRequestCode int = 400

/*GetIndexSearchBadRequest Bad Request

swagger:response getIndexSearchBadRequest
*/
type GetIndexSearchBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetIndexSearchBadRequestBody `json:"body,omitempty"`
}

// NewGetIndexSearchBadRequest creates GetIndexSearchBadRequest with default headers values
func NewGetIndexSearchBadRequest() *GetIndexSearchBadRequest {

	return &GetIndexSearchBadRequest{}
}

// WithPayload adds the payload to the get index search bad request response
func (o *GetIndexSearchBadRequest) WithPayload(payload *GetIndexSearchBadRequestBody) *GetIndexSearchBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index search bad request response
func (o *GetIndexSearchBadRequest) SetPayload(payload *GetIndexSearchBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexSearchBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIndexSearchNotFoundCode is the HTTP code returned for type GetIndexSearchNotFound
const GetIndexSearchNotFoundCode int = 404

/*GetIndexSearchNotFound Not Found

swagger:response getIndexSearchNotFound
*/
type GetIndexSearchNotFound struct {

	/*
	  In: Body
	*/
	Payload *GetIndexSearchNotFoundBody `json:"body,omitempty"`
}

// NewGetIndexSearchNotFound creates GetIndexSearchNotFound with default headers values
func NewGetIndexSearchNotFound() *GetIndexSearchNotFound {

	return &GetIndexSearchNotFound{}
}

// WithPayload adds the payload to the get index search not found response
func (o *GetIndexSearchNotFound) WithPayload(payload *GetIndexSearchNotFoundBody) *GetIndexSearchNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index search not found response
func (o *GetIndexSearchNotFound) SetPayload(payload *GetIndexSearchNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexSearchNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIndexSearchInternalServerErrorCode is the HTTP code returned for type GetIndexSearchInternalServerError
const GetIndexSearchInternalServerErrorCode int = 500

/*GetIndexSearchInternalServerError Internal Server Error

swagger:response getIndexSearchInternalServerError
*/
type GetIndexSearchInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *GetIndexSearchInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetIndexSearchInternalServerError creates GetIndexSearchInternalServerError with default headers values
func NewGetIndexSearchInternalServerError() *GetIndexSearchInternalServerError {

	return &GetIndexSearchInternalServerError{}
}

// WithPayload adds the payload to the get index search internal server error response
func (o *GetIndexSearchInternalServerError) WithPayload(payload *GetIndexSearchInternalServerErrorBody) *GetIndexSearchInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index search internal server error response
func (o *GetIndexSearchInternalServerError) SetPayload(payload *GetIndexSearchInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexSearchInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
