// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/future-architect/watertower/webapi/models"
)

// PostIndexDocOKCode is the HTTP code returned for type PostIndexDocOK
const PostIndexDocOKCode int = 200

/*PostIndexDocOK OK

swagger:response postIndexDocOK
*/
type PostIndexDocOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModifyResponse `json:"body,omitempty"`
}

// NewPostIndexDocOK creates PostIndexDocOK with default headers values
func NewPostIndexDocOK() *PostIndexDocOK {

	return &PostIndexDocOK{}
}

// WithPayload adds the payload to the post index doc o k response
func (o *PostIndexDocOK) WithPayload(payload *models.ModifyResponse) *PostIndexDocOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post index doc o k response
func (o *PostIndexDocOK) SetPayload(payload *models.ModifyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndexDocOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostIndexDocNotFoundCode is the HTTP code returned for type PostIndexDocNotFound
const PostIndexDocNotFoundCode int = 404

/*PostIndexDocNotFound Not Found

swagger:response postIndexDocNotFound
*/
type PostIndexDocNotFound struct {

	/*
	  In: Body
	*/
	Payload *PostIndexDocNotFoundBody `json:"body,omitempty"`
}

// NewPostIndexDocNotFound creates PostIndexDocNotFound with default headers values
func NewPostIndexDocNotFound() *PostIndexDocNotFound {

	return &PostIndexDocNotFound{}
}

// WithPayload adds the payload to the post index doc not found response
func (o *PostIndexDocNotFound) WithPayload(payload *PostIndexDocNotFoundBody) *PostIndexDocNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post index doc not found response
func (o *PostIndexDocNotFound) SetPayload(payload *PostIndexDocNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndexDocNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostIndexDocInternalServerErrorCode is the HTTP code returned for type PostIndexDocInternalServerError
const PostIndexDocInternalServerErrorCode int = 500

/*PostIndexDocInternalServerError Internal Server Error

swagger:response postIndexDocInternalServerError
*/
type PostIndexDocInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostIndexDocInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostIndexDocInternalServerError creates PostIndexDocInternalServerError with default headers values
func NewPostIndexDocInternalServerError() *PostIndexDocInternalServerError {

	return &PostIndexDocInternalServerError{}
}

// WithPayload adds the payload to the post index doc internal server error response
func (o *PostIndexDocInternalServerError) WithPayload(payload *PostIndexDocInternalServerErrorBody) *PostIndexDocInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post index doc internal server error response
func (o *PostIndexDocInternalServerError) SetPayload(payload *PostIndexDocInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndexDocInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
