// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/future-architect/watertower/webapi/models"
)

// PutIndexDocIDOKCode is the HTTP code returned for type PutIndexDocIDOK
const PutIndexDocIDOKCode int = 200

/*PutIndexDocIDOK OK

swagger:response putIndexDocIdOK
*/
type PutIndexDocIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModifyResponse `json:"body,omitempty"`
}

// NewPutIndexDocIDOK creates PutIndexDocIDOK with default headers values
func NewPutIndexDocIDOK() *PutIndexDocIDOK {

	return &PutIndexDocIDOK{}
}

// WithPayload adds the payload to the put index doc Id o k response
func (o *PutIndexDocIDOK) WithPayload(payload *models.ModifyResponse) *PutIndexDocIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put index doc Id o k response
func (o *PutIndexDocIDOK) SetPayload(payload *models.ModifyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIndexDocIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutIndexDocIDBadRequestCode is the HTTP code returned for type PutIndexDocIDBadRequest
const PutIndexDocIDBadRequestCode int = 400

/*PutIndexDocIDBadRequest Bad Request

swagger:response putIndexDocIdBadRequest
*/
type PutIndexDocIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PutIndexDocIDBadRequestBody `json:"body,omitempty"`
}

// NewPutIndexDocIDBadRequest creates PutIndexDocIDBadRequest with default headers values
func NewPutIndexDocIDBadRequest() *PutIndexDocIDBadRequest {

	return &PutIndexDocIDBadRequest{}
}

// WithPayload adds the payload to the put index doc Id bad request response
func (o *PutIndexDocIDBadRequest) WithPayload(payload *PutIndexDocIDBadRequestBody) *PutIndexDocIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put index doc Id bad request response
func (o *PutIndexDocIDBadRequest) SetPayload(payload *PutIndexDocIDBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIndexDocIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutIndexDocIDNotFoundCode is the HTTP code returned for type PutIndexDocIDNotFound
const PutIndexDocIDNotFoundCode int = 404

/*PutIndexDocIDNotFound Not Found

swagger:response putIndexDocIdNotFound
*/
type PutIndexDocIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *PutIndexDocIDNotFoundBody `json:"body,omitempty"`
}

// NewPutIndexDocIDNotFound creates PutIndexDocIDNotFound with default headers values
func NewPutIndexDocIDNotFound() *PutIndexDocIDNotFound {

	return &PutIndexDocIDNotFound{}
}

// WithPayload adds the payload to the put index doc Id not found response
func (o *PutIndexDocIDNotFound) WithPayload(payload *PutIndexDocIDNotFoundBody) *PutIndexDocIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put index doc Id not found response
func (o *PutIndexDocIDNotFound) SetPayload(payload *PutIndexDocIDNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIndexDocIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
